### ISSUE TITLE
Can't open issue in main repo...

### ISSUE THREAD

**Issue by lucasb-eyer** [lballes/msvag#1]
...since it is a fork of this one, and one can't open issues in forks by default.

I don't have an actual issue to open, just browsing and came across it and thought I'd let you know, since you write:

> If you have any questions or suggestions regarding this implementation, please open an issue

in the readme :smile: 

Cheers!

**Comment by lballes** [comment]
Hi!

Thanks for pointing this out. I will change the README to explicitly direct issues to lballes/msvag. 

Best,
Lukas
